language: node_js
node_js:
  - 16
cache:
  directories:
    - node_modules
scripts:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: &GITHUB_TOKEN
  local_dir: out
  on:
    all_branches: true